version: '3'

services:
  dynamic-table-in-quasar-framework:
    image: ramonteran/quasar-cli:1.0
    container_name: Dynamic-table-in-quasar-framework
    working_dir: /home/node/app/admin
    ports: 
      - "9100:9100"
    volumes: 
      - ./dynamic-table-in-quasar-framework:/home/node/app/admin
    restart: always
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: /bin/sh -c "yarn && quasar dev"

